Presentation.Site/Models/Presentation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Norm.Attributes;

namespace Projector.Site.Models
{
    public class Presentation
    {
        private readonly IList<Attendee> attendees;

        public Guid Id { get; protected set; }
        public string Title { get; protected set; }
        public string Permanent { get; protected set; }
        [MongoIgnore]
        public Attendee Speaker
        {
            get
            { return attendees.SingleOrDefault(attendee => attendee.Speaker); }
        }
        public string Description { get; set; }
        public int QtdSlides { get; set; }
        public IEnumerable<Attendee> Attendees
        {
            get { return attendees; }
        }

        public Presentation()
        {}

        public Presentation(string title, string description)
            : this()
        {
            Title = title;
            Description = description;
            Permanent = Regex.Replace(Title, @"[^(\w|0-9)]+", "");
            Id =  Guid.NewGuid();
            attendees = new List<Attendee>();
        }

        public void AddAttendee(Attendee attendee)
        {
            if (!attendees.Any(attendee.Equals))
            {
                attendees.Add(attendee);
            }
        }

        public bool SpeakerIs(Guid attendeId)
        {
            var speaker = Speaker;

            return speaker != null 
                ? speaker.Speaker : false;
        }
    }
}

Presentation.Site/Areas/Admin/Controllers/PresentationsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Projector.Site.Areas.Admin.Models;
using Projector.Site.Commands;
using Projector.Site.Models;
using Projector.Site.Repositories.Contract;

namespace Projector.Site.Areas.Admin.Controllers
{
    public class PresentationsController : Controller
    {
        private readonly IRepository<Presentation> presentations;
        private readonly ICommandHandler<Presentation> commandHandler;

        public PresentationsController()
        {
            presentations = new Repository<Presentation>();
            commandHandler = new CommandHandler<Presentation>();
        }


        public ActionResult Index()
        {
            return View(presentations.All());
        }

        public ActionResult Create()
        {
            return View(new PresentationFormViewModel());
        }

        [HttpPost]
        public ActionResult Create(PresentationFormViewModel presentationForm)
        {
            if(ModelState.IsValid)
            {
                var presentation = new Presentation(presentationForm.Title, presentationForm.Description);
                commandHandler
                    .Add(new FilePresentationCommand(presentationForm.PresentationFile))
                    .Add(new ConvertPresentationCommand())
                    .Process(presentation, (returns) => presentation.QtdSlides = returns.Last());

                presentations.Add(presentation);

                return RedirectToAction("Details", new{ id = presentation.Id });
            }
            return View(presentationForm);
        }

        public ActionResult Details(Guid id)
        {
            var presentation = presentations.FindOne(p => p.Id == id);
            return View(presentation);
        }
    }
}

Presentation.Site/Controllers/PresentationController.cs
using System;
using System.Dynamic;
using System.Linq;
using System.Web.Mvc;
using Projector.Site.Models;
using Projector.Site.Repositories;
using Projector.Site.Repositories.Contract;

namespace Projector.Site.Controllers
{
    public class PresentationController : Controller
    {
        private readonly IRepository<Presentation> presentations;

        public PresentationController()
        {
            presentations = new Repository<Presentation>();
        }

        public ActionResult Index()
        {
            var all = presentations.All();

            return View(all);
        }

        [Authorize]
        public ActionResult Show(string permanent)
        {
            var identity = (PresentationIdentity)User.Identity;
            var presenteation = presentations
                .FindOne(p => p.Permanent == permanent);
            
            var attendee = presenteation
                .Attendees
                .SingleOrDefault(a => a.Email.Equals(identity.UserName));

            ViewBag.Presentation = presenteation;
            ViewBag.Attendee = attendee;

            return View();
        }
    }
}

Presentation.Site/Areas/Admin/Views/Presentations/Create.cshtml
@model Projector.Site.Areas.Admin.Models.PresentationFormViewModel

@{
    ViewBag.Title = "Create";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h2>Create</h2>

@using (Html.BeginForm("Create", "Presentations", FormMethod.Post, new { area = "admin", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Presentation</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.Label("Presentation")
        </div>
        <div class="editor-field">
            <input type="file" name="PresentationFile" />
            @Html.ValidationMessageFor(model => model.PresentationFile)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Presentation.Site/Areas/Admin/Views/Presentations/Details.cshtml
@model Projector.Site.Models.Presentation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Presentation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>

<div>
    <ul id="tabs">
        <li><a href="#tabs-slides">Slides</a></li>
        <li><a href="#tabs-attendees">Attendees</a></li>
    </ul>
    
    <div id="tabs-container">
        <div id="tabs-slides">
            <h2>Slides</h2>
            <div>
                <ul id="container-slides">
                    @for (var slide = 1; slide < Model.QtdSlides; slide++ )
                    {
                        <li><img src="@Url.Content(string.Format("~/Slides/{0}/slide{1}.png", Model.Id, slide))" /></li>
                    }
                </ul>
            </div>
        </div>

        <div id="tabs-attendees">
            <h2>Attendees</h2>
            <a href="@Url.RouteUrl("Admin_attendee", new { presentationid = @Model.Id, action = "Add" })">Add Attendde</a>
            <div class="container-attendees">
                <ul>
                    @foreach (var attendee in Model.Attendees)
                    {
                        <li class="@(attendee.Speaker ? "speaker" : "attendee")">
                            <img src="@attendee.GravatarUrl" alt="@attendee.Name" />
                            <a  href="mailto:@attendee.Email">@attendee.Name</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>


<p class="container-botoes">
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<script type="text/javascript">
    $(document).ready(function () {
        $("#tabs").simpletabs();
    });
</script>

Presentation.Site/Areas/Admin/Views/Presentations/Edit.cshtml
@model Projector.Site.Models.Presentation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Presentation</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Presentation.Site/Areas/Admin/Views/Presentations/Index.cshtml
@model IEnumerable<Projector.Site.Models.Presentation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<br />
<table>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>       
            <td colspan="2">
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>            
        </tr>
        <tr>
             <td colspan="3">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
        }
    </tbody>
</table>